# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 674)
        MainWindow.setStyleSheet("background-color: #121212;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 411, 681))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalFrame_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.verticalFrame_2.setStyleSheet("border-radius: 20px;\n"
"")
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalFrame_3 = QtWidgets.QFrame(self.verticalFrame_2)
        self.verticalFrame_3.setStyleSheet("background-color: #2C2C2C;")
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalFrame_3)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.verticalFrame_3)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"margin-left: 85px;")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.btnUsuario = QtWidgets.QLineEdit(self.verticalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUsuario.sizePolicy().hasHeightForWidth())
        self.btnUsuario.setSizePolicy(sizePolicy)
        self.btnUsuario.setStyleSheet("border: 2px solid white;\n"
"margin-left: 90px;\n"
"color: white;")
        self.btnUsuario.setFrame(True)
        self.btnUsuario.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.btnUsuario.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.btnUsuario.setObjectName("btnUsuario")
        self.verticalLayout_4.addWidget(self.btnUsuario)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.verticalFrame_3)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"margin-left: 85px;")
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.btnSenha = QtWidgets.QLineEdit(self.verticalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSenha.sizePolicy().hasHeightForWidth())
        self.btnSenha.setSizePolicy(sizePolicy)
        self.btnSenha.setStyleSheet("border: 2px solid white;\n"
"margin-left: 90px;\n"
"color: white;")
        self.btnSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.btnSenha.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.btnSenha.setObjectName("btnSenha")
        self.verticalLayout_5.addWidget(self.btnSenha)
        spacerItem2 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnEntrar = QtWidgets.QPushButton(self.verticalFrame_3)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnEntrar.setFont(font)
        self.btnEntrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEntrar.setStyleSheet("QPushButton:hover {\n"
"    background-color: #FF5C5C;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 0px;\n"
"    height: 50px;\n"
"    background-color: #B0060F;\n"
"    color: white;\n"
"}")
        self.btnEntrar.setFlat(True)
        self.btnEntrar.setObjectName("btnEntrar")
        self.horizontalLayout_5.addWidget(self.btnEntrar)
        self.btnCadastrar = QtWidgets.QPushButton(self.verticalFrame_3)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnCadastrar.setFont(font)
        self.btnCadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCadastrar.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 20px;\n"
"    height: 50px;\n"
"    background-color: #B0B0B0;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(121, 121, 121);\n"
"}")
        self.btnCadastrar.setFlat(True)
        self.btnCadastrar.setObjectName("btnCadastrar")
        self.horizontalLayout_5.addWidget(self.btnCadastrar)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addWidget(self.verticalFrame_3)
        self.verticalLayout_2.addWidget(self.verticalFrame_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label_3.setText(_translate("MainWindow", "CineList"))
        self.label.setText(_translate("MainWindow", "Usuário"))
        self.label_2.setText(_translate("MainWindow", "Senha"))
        self.btnEntrar.setText(_translate("MainWindow", "Entrar"))
        self.btnCadastrar.setText(_translate("MainWindow", "Cadastrar"))

from utils import verificar_login

def conectar_sinais(self):
    self.btnEntrar.clicked.connect(self.tentar_login)
    self.btnCadastrar.clicked.connect(self.abrir_cadastro)

def tentar_login(self):
    usuario = self.btnUsuario.text()
    senha = self.btnSenha.text()
    if verificar_login(usuario, senha):
        from telaprincipal import Ui_MainWindow as PrincipalUi
        self.janela = QtWidgets.QMainWindow()
        self.uiPrincipal = PrincipalUi()
        self.uiPrincipal.setupUi(self.janela)
        self.janela.show()
        self.MainWindow.close()
    else:
        QtWidgets.QMessageBox.warning(self.MainWindow, "Erro", "Usuário ou senha inválido!")

def abrir_cadastro(self):
    from cadastrar import Ui_MainWindow as CadastroUi
    self.janelaCadastro = QtWidgets.QMainWindow()
    self.uiCadastro = CadastroUi()
    self.uiCadastro.setupUi(self.janelaCadastro)
    self.janelaCadastro.show()
    self.MainWindow.close()
