# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 674)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(402, 674))
        MainWindow.setMaximumSize(QtCore.QSize(402, 674))
        MainWindow.setStyleSheet("background-color: #121212;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 402, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: #1E1E1E;\n"
"color: white;\n"
"border-bottom-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 0px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 411, 631))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    width: 201px;\n"
"    height: 50px;\n"
"    background-color: #1E1E1E;\n"
"    color: #FFFFFF;\n"
"    border-top: 3px solid #B0060F;\n"
"} ")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabFilmes = QtWidgets.QWidget()
        self.tabFilmes.setObjectName("tabFilmes")
        self.scrollArea = QtWidgets.QScrollArea(self.tabFilmes)
        self.scrollArea.setGeometry(QtCore.QRect(-1, -1, 421, 591))
        self.scrollArea.setStyleSheet("QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 419, 589))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutFilmes = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.layoutFilmes.setContentsMargins(10, 40, 10, 40)
        self.layoutFilmes.setSpacing(15)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tabFilmes, "")
        self.tabSeries = QtWidgets.QWidget()
        self.tabSeries.setObjectName("tabSeries")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tabSeries)
        self.scrollArea_2.setGeometry(QtCore.QRect(-1, -1, 421, 591))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 419, 589))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.layoutSeries = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.layoutSeries.setContentsMargins(10, 10, 10, 10)
        self.layoutSeries.setSpacing(15)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.tabSeries, "")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 550, 401, 57))
        self.horizontalLayoutWidget.setStyleSheet("background: transparent;")
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAdicionar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnAdicionar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdicionar.sizePolicy().hasHeightForWidth())
        self.btnAdicionar.setSizePolicy(sizePolicy)
        self.btnAdicionar.setMinimumSize(QtCore.QSize(55, 55))
        self.btnAdicionar.setMaximumSize(QtCore.QSize(55, 55))
        self.btnAdicionar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAdicionar.setStyleSheet("border: none;\n"
"background-color: transparent;\n"
"")
        self.btnAdicionar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagens/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdicionar.setIcon(icon1)
        self.btnAdicionar.setIconSize(QtCore.QSize(55, 55))
        self.btnAdicionar.setObjectName("btnAdicionar")
        self.horizontalLayout.addWidget(self.btnAdicionar)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tabWidget.raise_()
        self.label_3.raise_()
        self.horizontalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CineList"))
        self.label_3.setText(_translate("MainWindow", "CineList"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFilmes), _translate("MainWindow", "Filmes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSeries), _translate("MainWindow", "Séries"))